version: '3.7'
services:

  db:
    image: mysql:8.0.31

    environment:
      - MYSQL_ROOT_PASSWORD=password

    ports:
      - '3306:3306'

    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro

    networks:
      - backend

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
    - 8080:80
    volumes:
      - type: bind
        source: ./app/src
        target: /usr/app/src
    networks:
      - backend

    depends_on:
      - db

networks:
  backend: