version: '3.7'
services:

  db:
    image: mysql:8.0.31

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

    ports:
      - '3306:3306'

    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro

    networks:
      - backend

    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: ./app
      dockerfile: Dockerfile

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

    ports:
    - 8080:80

    volumes:
      - type: bind
        source: ./app/src
        target: /usr/app/src

    networks:
      - backend

    depends_on:
      db:
        condition: service_healthy

networks:
  backend: