version: '3.7'
services:

  db:
    image: mysql:8.0.31

    container_name: ${DB_CONTAINER_NAME}

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

    ports:
      - '3306:3306'

    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    networks:
      - backend

    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: ./app
      dockerfile: Dockerfile

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - TABLE_NAME=${TABLE_NAME}
      - IMGUR_API_CLIENT_ID=${IMGUR_API_CLIENT_ID}
      - IMGUR_API_CLIENT_SECRET=${IMGUR_API_CLIENT_SECRET}

    ports:
      - 8080:8080

    volumes:
      - type: bind
        source: ./app/src
        target: /usr/app/src
      - type: bind
        source: ./app/data_backups
        target: /usr/app/data_backups
      - type: bind
        source: ./common_info
        target: /usr/app/common_info

    networks:
      - backend

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
    - 3000:3000

    volumes:
      - type: bind
        source: ./frontend/src
        target: /usr/frontend/src
      - type: bind
        source: ./frontend/public
        target: /usr/frontend/public
      - type: bind
        source: ./common_info
        target: /usr/frontend/src/common_info
    
    networks:
      - backend


networks:
  backend: